services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: db1234

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db
